import { getDayOfYear } from "date-fns";
import type { Prompt } from "./types";

export const PROMPT_CATEGORIES: Record<string, string[]> = {
  gratitude: [
    "What small thing today would you miss if it were gone tomorrow?",
    "Who made your day a little easier — and do they know?",
    "What's one thing about your home that you're quietly glad about?",
    "Name something your body did for you today without you asking.",
    "What's a comfort you've stopped noticing?",
    "What's something free that brought you real pleasure today?",
    "Who is someone you've never thanked properly?",
    "What season of life are you in right now — and what's good about it?",
    "What did you eat today that was genuinely satisfying?",
    "What's a sound you heard today that you actually liked?",
    "What's one thing about your daily routine that quietly works?",
    "What part of today felt the most like you?",
    "What's a recent kindness someone showed you — even a tiny one?",
    "If you could bottle one moment from today, which would it be?",
    "What's something about this week that last-year-you would be glad about?",
  ],
  creativity: [
    "If you could spend tomorrow doing anything creative, what would it be?",
    "What's something you used to make or do that you miss?",
    "Describe the view from your favourite window in your house.",
    "What's the last thing you saw that you thought was beautiful?",
    "If your current mood were a weather system, what would it be?",
    "Write about a colour that keeps showing up in your life lately.",
    "What's a skill you'd love to learn if time didn't matter?",
    "Describe a memory using only what you could hear, smell, and feel.",
    "What would your dream Saturday morning look like, hour by hour?",
    "If you wrote a one-sentence memoir of this month, what would it say?",
    "What song has been stuck in your head — and why do you think it chose you?",
    "Describe your ideal workspace. What's different from what you have now?",
    "If your life right now were a book chapter, what would the title be?",
    "What's something ugly that you find oddly beautiful?",
    "Write three sentences about your day as if you were a novelist.",
  ],
  relationships: [
    "What's something your partner did recently that you noticed but didn't mention?",
    "When did you last laugh really hard with someone?",
    "Who do you wish you could talk to more often?",
    "What's a conversation you've been putting off?",
    "What's the nicest thing someone said to you this week?",
    "How did you show up for someone today — even in a small way?",
    "What's a friendship you've let drift that you think about sometimes?",
    "What does your partner need from you right now that isn't being said?",
    "When did you last feel truly listened to?",
    "Who surprised you recently — in a good way?",
    "What's one thing you could do tomorrow to make someone's day?",
    "Describe a moment of real connection you had this week.",
    "What's something about your relationship that you'd never trade?",
    "Who taught you something important without realising it?",
    "What's a boundary you need to set — or one you're glad you did?",
  ],
  work_and_purpose: [
    "What part of your work felt meaningful today?",
    "What are you avoiding at work — and what's behind the avoidance?",
    "If you could redesign your workday from scratch, what would change?",
    "What's a problem you're solving that actually matters?",
    "When did you last feel in flow — fully absorbed in something?",
    "What's one thing about your job that your younger self would be proud of?",
    "What would you do differently if nobody was watching?",
    "What's draining your energy at work right now?",
    "If you could master one skill in your field, what would it be?",
    "What did you learn this week that you didn't know before?",
    "What's a win you haven't celebrated yet?",
    "Describe the best working day you've had in the last month.",
    "What would you do for work if money were irrelevant?",
    "What's the hardest decision you're facing professionally?",
    "What kind of impact do you want your work to have in five years?",
  ],
  body_and_rest: [
    "How did your body feel when you woke up this morning?",
    "What's one kind thing you did for your body today?",
    "When did you last sleep deeply and well — what was different?",
    "What does your body need right now that you're ignoring?",
    "Describe a meal that made you feel genuinely nourished.",
    "What's your relationship with rest like right now — honest answer?",
    "What physical sensation do you notice most often in a day?",
    "When did you last move your body in a way that felt good, not dutiful?",
    "What time of day do you feel most alive?",
    "What's one thing you wish you could change about your sleep?",
    "How does stress show up in your body?",
    "What helps you actually unwind — not just distract?",
    "Describe what relaxation looks like for you right now.",
    "What's a physical space where you feel your shoulders drop?",
    "If your energy level were a phone battery, what percentage are you at?",
  ],
  family: [
    "What moment with your kids made you stop today?",
    "What's something your child said recently that stuck with you?",
    "How are you doing as a parent — honestly, not performatively?",
    "What's one thing about family life that nobody warns you about?",
    "What does your kid need from you right now that's hard to give?",
    "Describe a mundane family moment that was secretly lovely.",
    "What kind of parent do you want to be this week?",
    "What family rhythm is working right now — and which one isn't?",
    "What did you inherit from your own parents that you want to keep? What do you want to leave behind?",
    "What's the funniest thing that happened at home recently?",
    "How do you and your partner divide the invisible work — is it fair?",
    "What's a family tradition you want to start?",
    "What does your home sound like at its best?",
    "What's something about your family that would surprise an outsider?",
    "If your kids could only remember one thing about you, what would you want it to be?",
  ],
  big_picture: [
    "What are you most afraid of right now — and is it real or imagined?",
    "What would 80-year-old you say about how you're spending your time?",
    "What belief have you changed your mind about recently?",
    "What's something you're holding onto that you could let go of?",
    "Where do you feel most like yourself?",
    "What's one thing you know is true that most people around you would disagree with?",
    "What does enough look like for you right now?",
    "If you had six months off with no obligations, what would you do first?",
    "What are you building — consciously or not?",
    "What question do you wish someone would ask you?",
    "What's the gap between who you are and who you pretend to be?",
    "What would you do if you weren't afraid of being judged?",
    "What season of life are you in — and are you fighting it or leaning in?",
    "What do you want more of? What do you want less of?",
    "What does a good life look like to you — not the internet's version, yours?",
  ],
  fun_and_play: [
    "When did you last do something just because it was fun?",
    "What did you love doing as a kid that you've stopped doing?",
    "What's the most ridiculous thing that made you laugh this week?",
    "If you could learn any instrument overnight, which would it be?",
    "What's a guilty pleasure you're not actually guilty about?",
    "What's the last thing you watched or read that you couldn't put down?",
    "If you could have dinner with anyone — living or dead — who and why?",
    "What game do you wish you played more often?",
    "What's something playful you could add to your morning?",
    "What would you do this weekend if you had zero responsibilities?",
    "Describe your ideal adventure day — from start to finish.",
    "What's a hobby you've always been curious about but never tried?",
    "What's the best trip or outing you've had in the last year?",
    "If you could have any superpower for just one day, what would you pick?",
    "What's something silly that makes you disproportionately happy?",
  ],
};

export function getAllPrompts(): Prompt[] {
  return Object.entries(PROMPT_CATEGORIES).flatMap(([category, prompts]) =>
    prompts.map((text) => ({ category, text }))
  );
}

export function getTodaysPrompt(date: Date = new Date()): Prompt {
  const dayOfYear = getDayOfYear(date);
  const allPrompts = getAllPrompts();
  return allPrompts[dayOfYear % allPrompts.length];
}
